---
- name: Deploy dockerized application
  hosts: dockervm
  become: yes

  tasks:

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Ensure pip3 is installed
      apt:
        name: python3-pip
        state: present

    - name: Install Docker SDK for Python
      pip:
        name: docker

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker image
      docker_image:
        name: parasoft/demo-app
        source: pull

    - name: Run Docker container
      docker_container:
        name: web-app-demo
        image: parasoft/demo-app
        state: started
        ports:
          - "8080:8080"

    - name: Restart Apache2 service
      systemd:
        name: apache2
        state: restarted
        enabled: yes

